# Generated by Django 5.2 on 2025-10-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_refs', to='items.item'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='items.item'),
        ),
    ]
